#!/bin/bash

# Backup script
#### You have to be in the folder, that contains the directories to backup ####
BPATH="$HOME/backups"	# For sucsessful backup you need to be in the folder that you want to backup
GPATH="$HOME/Google Drive"	# Google Drive backup, works only if you have installed Google Drive

backup()	# For sucsessful backup you need to be in the folder that you want to backup
{
	if [ ! -d "${BPATH}/$*" ];
		then
			echo "Bakuping to ${BPATH}/$*"
			mkdir -p ${BPATH}/$*/
		else
			echo "Rewriting bakup to ${BPATH}/$*/"
			if [ ! -d "${BPATH}/_old" ];
				then
					mkdir -p ${BPATH}/_old
			fi
			if [ -d ${BPATH}/_old/$*/ ] && [ -d ${BPATH}/$*/ ];
				then
					rm -rf ${BPATH}/_old/$*/
					mkdir -p ${BPATH}/_old/$*/
					mv ${BPATH}/$*/* ${BPATH}/_old/$*/
				else
					mkdir -p ${BPATH}/_old/$*/
					mv ${BPATH}/$*/* ${BPATH}/_old/$*/
			fi
	fi
	cp -r $*/* ${BPATH}/$*/
}

delbackup()
{
	if [ -d "${BPATH}/$*" ];
		then
			echo "Deleting backup from ${BPATH}/$*"
			rm -rf ${BPATH}/$*
		else
			echo "Backup ${BPATH}/$* doesn't exist"
	fi
}

backup_restore()
{
	if [ -d "${BPATH}/$*" ];
		then
			echo "Getting backup from ${BPATH}/$*"
			cp -r ${BPATH}/$*/ .
		else
			echo "Backup ${BPATH}/$* doesn't exist"
	fi
}

gdbackup()	# Google Drive backup, works only if you have installed Google Drive suddenly
{
	if [ -e "${GPATH}/$*.zip" ];
		then
			echo "Rewriting backup to ${GPATH}/$*.zip"
			rm -rf $*.zip
		else
			echo "Writing backup to ${GPATH}/$*.zip"
	fi
	zip -qr $*.zip $*
	mv $*.zip ${GPATH}/
}

alias bak=backup
alias gbak=gdbackup
alias delbak=delbackup
alias bakre=backup_restore
